ConfigVersion: 1

#Should avatar images be saved to reduce the load on the avatar service
CacheImages: true
#Time in hours that an image should be used from the cache, a new image will be downloaded after the cached version expires
CacheTimeout: 2

#This will send the message 5 game ticks (1/4 of a second) later so that it appears after any other messages
DelayMessage: false

#URL for fetching the users avatar, should ideally provide an image with dimensions 8x8
AvatarURL: "https://crafatar.com/avatars/%UUID%?size=8&default=MHF_Steve&overlay"